### ISSUE TITLE
Note missing from device

### ISSUE THREAD

**Issue by NoelDeMartin** [wikiavec/hyperdraft#4]
I've been using Hyperdraft for a while and so far it is working great :).

Recently I noticed a note I have in my computer does not appear in my phone. Just to test, I tried creating a new note in both devices, and they appeared correctly in the other device. So there is something about this particular note that is keeping it from syncing. I created it some days ago and I have updated it multiple times since.

Let me know how can I debug to give you more information. I suppose the issue is that the note is only kept locally, fortunately it's on the desktop device so I can inspect some network request or indexedDB/localStorage if needed.

**Comment by rosano** [comment]
Seems like you may have found this remotestorage.js bug:
- https://github.com/remotestorage/remotestorage.js/issues/1187
- https://github.com/remotestorage/remotestorage.js/issues/1188

I think at some stage it syncs but doesn't cache the object somehow, and fails to ever fetch again. It seems also like this doesn't happen on a fresh start but after using it 'for a while' as you mentioned, which complicates replicating the issue.

Anyway, I'm glad you've been using Hyperdraft and also sort of glad you found this. I suspect that rather than being 'kept locally', it *has* been synced to the server, but for some reason fails to add to other devices (you can try signing in via a private tab to confirm if it's on the server). At the moment, the only solutions I'm aware of are:
- sign out, refresh, sign in
- when the document syncs to the new device, 'touch' it by editing something to make sure it stays (🙄)

Unfortunately this problem exists in all my apps when using remoteStorage. I thought it was because I use Safari, but it seems like it happens with Firefox as well, perhaps less often. Very mysterious and hard to track down. Maybe share your experience in those threads?
